name: Zig compatibility

on:
  push:
    branches: [main, zig016-miz-compat]
  pull_request:

permissions:
  contents: read
  attestations: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: cataggar/ghr/actions/install@c4be68b52d67d7acd2a7fe6c1e5f126e1754176e
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          ghr-version: v0.8.1
          tools: >-
            cataggar/zig@v0.17.0
            RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U
      - run: zig build -j2 ci
      - run: zig build -j2 -Doptimize=safe test
      - run: zig fmt --check build.zig src
